# Validation Robotics Core

## Import Modules

In [65]:
import importlib
import numpy as np
import RoboticsCore as r
importlib.reload(r)

<module 'RoboticsCore' from 'd:\\MECH639\\mech639_pybullet\\RoboticsCore.py'>

## se3 -> SE3 --> PASS

In [45]:
#se3mat = np.array([[0, 0, 0, 0], [0, 0, -1.57079632, 2.35619449], [0, 1.57079632, 0, 2.35619449], [0, 0, 0, 0]])
#se3mat = np.array([[0, 0, 0, 0], [0, 0, -1.570, 2.356], [0, 1.570, 0, 2.356], [0, 0, 0, 0]]) # Pitch h=0
se3mat = np.array([[0, 0, 0, 3], [0, 0, 1.0, 2.0], [0, -1.0, 0, 10.0], [0, 0, 0, 0]])
print(r.MatrixExp6(se3mat, formula=1))
print(r.MatrixExp6(se3mat, formula=2))
print(r.MatrixExp6(se3mat, formula=1)-r.MatrixExp6(se3mat, formula=2))

[[ 1.          0.          0.          3.        ]
 [ 0.          0.54030231  0.84147098  6.27991891]
 [ 0.         -0.84147098  0.54030231  7.49531446]
 [ 0.          0.          0.          1.        ]]
[[ 1.          0.          0.          3.        ]
 [ 0.          0.54030231  0.84147098  6.27991891]
 [ 0.         -0.84147098  0.54030231  7.49531446]
 [ 0.          0.          0.          1.        ]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.8817842e-16]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]


## FK and IK Body 3DOF --> PASS

In [80]:
M = np.array([[-1, 0, 0, 0],[ 0, 1, 0, 6], [ 0, 0, -1, 2], [ 0, 0, 0, 1]])
Blist = np.array([[2, 0, 0, 0, 0, -1],[0, 1, 0, 0, 0, 0], [0, 0, 0.1, 0, 0, 1]]).T
thetalist = np.array([np.pi / 2.0, 3, np.pi])
T = r.FKinBody(M, Blist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: ", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.array([1.5, 2.5, 3])
thetalist_IK = r.IKinBody(Blist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(deg): ", thetalist_IK[0]*(180/np.pi))

print(">>> Diff between FK-IK: ",(thetalist-thetalist_IK[0])*(180/np.pi))


>>> Theta for FK(deg):  [ 90.         171.88733854 180.        ]
>>> Result of FK:  [[-1.14423775e-17  1.00000000e+00  0.00000000e+00 -5.00000000e+00]
 [ 1.00000000e+00  1.14423775e-17  0.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  1.01303956e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Result of IK(deg):  [ 89.99939868 171.88733251 180.00880019]
>>> Diff between FK-IK:  [ 6.01319206e-04  6.02790496e-06 -8.80019029e-03]


## FK and IK Space 3DOF --> PASS

In [149]:
M = np.array([[-1, 0, 0, 0],[ 0, 1, 0, 6], [ 0, 0, -1, 2], [ 0, 0, 0, 1]])
Slist = np.array([[ 4, 0, 0, 0, 0, 1],[ 0, 1, 0, 0, 0, 0], [-6, 0, -0.1, 0, 0, -1]]).T
thetalist = np.array([np.pi / 2.0, 3, np.pi])
T = r.FKinSpace(M,Slist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: ", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.array([1.5, 2.5, 3])
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(deg): ", thetalist_IK[0]*(180/np.pi))
print(">>> Diff between FK-IK: ",(thetalist-thetalist_IK[0])*(180/np.pi))

>>> Theta for FK(deg):  [ 90.         171.88733854 180.        ]
>>> Result of FK:  [[-1.14423775e-17  1.00000000e+00  0.00000000e+00 -5.00000000e+00]
 [ 1.00000000e+00  1.14423775e-17  0.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  1.01303956e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Result of IK(deg):  [ 89.4380083  167.47737327 178.20793748]
>>> Diff between FK-IK:  [0.5619917  4.40996527 1.79206252]


# Validation Using IndyRP2 Info

## FK and IK Body 7 DOF --> FAIL

In [135]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Blist = np.array([[0.1864,	0,0,	0,	0,	1],[0.9675,	0,	0,	0,	-1,	0],[-0.0073,	0,	0,	0,	0,	1],[0.518,	0,	0,	0,	-1,	0],[0.183,	0,	0,	0,	0,	1],[0.168,	0,	0,	0,	-1,	0],[0,	0,	0,	0,	0,	1]]).T
thetalist = np.ones(7)*np.pi/2.0
T = r.FKinBody(M,Blist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: \n", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.zeros(7)
thetalist_IK = r.IKinBody(Blist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(deg): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)])
print(">>> Result of IK(deg,%): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)%360])
print(">>> Diff between FK-IK(deg): ",[round(x,2) for x in (thetalist*(180/np.pi)-(thetalist_IK[0]*(180/np.pi)%360))])

TT = r.FKinBody(M,Blist,thetalist_IK[0])
print(">>> Result of FK': \n", TT)
print(">>> Diff between FK-IK(T): \n",T-TT)


>>> Theta for FK(deg):  [90. 90. 90. 90. 90. 90. 90.]
>>> Result of FK: 
 [[ 3.33066907e-16 -1.00000000e+00  2.22044605e-16 -1.56300000e-01]
 [ 1.00000000e+00  3.33066907e-16  2.22044605e-16  2.66500000e-01]
 [-2.22044605e-16  2.22044605e-16  1.00000000e+00  1.87620000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Result of IK(deg):  [-163.5, 1050.16, 213.55, -1323.39, 34.16, 164.41, 2261.44]
>>> Result of IK(deg,%):  [196.5, 330.16, 213.55, 116.61, 34.16, 164.41, 101.44]
>>> Diff between FK-IK(deg):  [-106.5, -240.16, -123.55, -26.61, 55.84, -74.41, -11.44]
>>> Result of FK': 
 [[-0.36378699 -0.7799445   0.50925986  0.07130091]
 [ 0.81915148 -0.00759334  0.57352697  0.339759  ]
 [-0.44345223  0.62580262  0.64165505  2.05243979]
 [ 0.          0.          0.          1.        ]]
>>> Diff between FK-IK(T): 
 [[ 0.36378699 -0.2200555  -0.50925986 -0.22760091]
 [ 0.18084852  0.00759334 -0.57352697 -0.073259  ]
 [ 0.44345223 -0.62580262  0.35834495 -0.176239

## FK and IK Space 7 DOF --> FAIL

In [136]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Slist = np.array([[0,0,0,0,0,1],[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T
thetalist = np.ones(7)*np.pi/2.0
T = r.FKinSpace(M,Slist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: \n", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.zeros(7)
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(deg): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)])
print(">>> Result of IK(deg,%): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)%360])
print(">>> Diff between FK-IK(deg): ",[round(x,2) for x in (thetalist*(180/np.pi)-(thetalist_IK[0]*(180/np.pi)%360))])

TT = r.FKinSpace(M,Slist,thetalist_IK[0])
print(">>> Result of FK': \n", TT)
print(">>> Diff between FK-IK(T): \n",T-TT)

>>> Theta for FK(deg):  [90. 90. 90. 90. 90. 90. 90.]
>>> Result of FK: 
 [[ 3.33066907e-16 -1.00000000e+00  2.22044605e-16 -1.56300000e-01]
 [ 1.00000000e+00  3.33066907e-16  2.22044605e-16  2.66500000e-01]
 [-2.22044605e-16  2.22044605e-16  1.00000000e+00  1.87620000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Result of IK(deg):  [8617.19, 1196.01, 4534.77, -8680.06, -1909.45, -1095.38, -1443.58]
>>> Result of IK(deg,%):  [337.19, 116.01, 214.77, 319.94, 250.55, 344.62, 356.42]
>>> Diff between FK-IK(deg):  [-247.19, -26.01, -124.77, -229.94, -160.55, -254.62, -266.42]
>>> Result of FK': 
 [[ 0.40112622  0.79219394 -0.45992013 -0.83845786]
 [ 0.90637979 -0.41591019  0.0741241  -0.14256233]
 [-0.13256481 -0.44659543 -0.88486106 -1.7346533 ]
 [ 0.          0.          0.          1.        ]]
>>> Diff between FK-IK(T): 
 [[-0.40112622 -1.79219394  0.45992013  0.68215786]
 [ 0.09362021  0.41591019 -0.0741241   0.40906233]
 [ 0.13256481  0.44659543  1.884

## FK in Body and Space 7 DOF --> PASS

In [137]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Blist = np.array([[0.1864,	0,0,	0,	0,	1],[0.9675,	0,	0,	0,	-1,	0],[-0.0073,	0,	0,	0,	0,	1],[0.518,	0,	0,	0,	-1,	0],[0.183,	0,	0,	0,	0,	1],[0.168,	0,	0,	0,	-1,	0],[0,	0,	0,	0,	0,	1]]).T
Slist = np.array([[0,0,0,0,0,1],[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T

thetalist = np.ones(7)*np.pi/2.0
Ts = r.FKinSpace(M,Slist,thetalist)
Tb = r.FKinBody(M,Blist,thetalist)
print(">>> Result of FKBody': \n", Tb)
print(">>> Result of FKSpace': \n", Ts)
print(">>> Diff between Tb-Ts: \n",Tb-Ts)


>>> Result of FKBody': 
 [[ 3.33066907e-16 -1.00000000e+00  2.22044605e-16 -1.56300000e-01]
 [ 1.00000000e+00  3.33066907e-16  2.22044605e-16  2.66500000e-01]
 [-2.22044605e-16  2.22044605e-16  1.00000000e+00  1.87620000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Result of FKSpace': 
 [[ 3.33066907e-16 -1.00000000e+00  2.22044605e-16 -1.56300000e-01]
 [ 1.00000000e+00  3.33066907e-16  2.22044605e-16  2.66500000e-01]
 [-2.22044605e-16  2.22044605e-16  1.00000000e+00  1.87620000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Diff between Tb-Ts: 
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -9.99200722e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.88578059e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


## IK in Body and Space 7 DOF --> FAIL

In [148]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Blist = np.array([[0.1864,	0,0,	0,	0,	1],[0.9675,	0,	0,	0,	-1,	0],[-0.0073,	0,	0,	0,	0,	1],[0.518,	0,	0,	0,	-1,	0],[0.183,	0,	0,	0,	0,	1],[0.168,	0,	0,	0,	-1,	0],[0,	0,	0,	0,	0,	1]]).T
Slist = np.array([[0,0,0,0,0,1],[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T

thetalist = np.ones(7)*np.pi/2.0
Ts = r.FKinSpace(M,Slist,thetalist)

eomg = 0.0001
ev = 0.0001
thetalist0 = thetalist - np.random.rand(7)*0.0001

thetalist_IKs = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
thetalist_IKb = r.IKinBody(Blist, M, T, thetalist0, eomg, ev)

print(">>> Result of IKs(deg,%): ", [round(x,2) for x in thetalist_IKs[0]*(180/np.pi)%360])
print(">>> Result of IKb(deg,%): ", [round(x,2) for x in thetalist_IKb[0]*(180/np.pi)%360])
print(">>> Diff between IKs-IKb(deg): ",[round(x,2) for x in ((thetalist_IKs[0]*(180/np.pi)%360)-(thetalist_IKb[0]*(180/np.pi)%360))])

>>> Result of IKs(deg,%):  [241.83, 8.48, 36.26, 145.48, 235.25, 253.94, 284.94]
>>> Result of IKb(deg,%):  [90.01, 90.0, 89.99, 90.0, 90.0, 90.01, 90.0]
>>> Diff between IKs-IKb(deg):  [151.83, -81.52, -53.73, 55.49, 145.24, 163.93, 194.95]


# 7 DOF

In [106]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,0,0,0,0,0,0]
T = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,30,0,-60,0,30,0]
# T = np.array([
#     [1, 0, 0,        -0.0497],
#     [ 0, 1, 0, -0.1864],
#     [ 0, 0, 1,  1.1599],
#     [ 0, 0, 0,       1]])

# T = np.array([
#     [ 0, 0,-1, -0.9675],
#     [ 0, 1, 0, -0.1864], 
#     [ 1, 0, 0,  0.2995], 
#     [ 0, 0, 0,       1]])

Slist = np.array([[0,0,0,0,0,1],[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T
eomg = 999999
ev = 0.001
thetalist0 = np.array([0,0,np.pi/2.0,0,0,0,0])
#thetalist0 = np.ones(7)*np.pi/0.001
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(rad): ", thetalist_IK[0])
print(">>> Result of IK(deg): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi))))
print(">>> Result of IK(deg,%): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

>>> Result of IK(rad):  [-152.13030523   64.79403474 -138.29620881  -58.42568669  145.57403555
   19.69317382  -14.75529024]
>>> Result of IK(deg):  -8716.4244255022,3712.4247280368013,-7923.789087531694,-3347.5452625855914,8340.777843654909,1128.3357448397853,-845.4158559876978
>>> Result of IK(deg,%):  283.5755744977996,112.4247280368013,356.21091246830565,252.45473741440856,60.77784365490879,48.33574483978532,234.5841440123022


In [121]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,0,0,0,0,0,0]
T = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,30,0,-60,0,30,0]
# T = np.array([
#     [1, 0, 0,        -0.0497],
#     [ 0, 1, 0, -0.1864],
#     [ 0, 0, 1,  1.1599],
#     [ 0, 0, 0,       1]])

# [0,45,0,-90,0,45,0]
# T = np.array([
#     [1, 0, 0,  -0.0704],
#     [ 0, 1, 0, -0.1864],
#     [ 0, 0, 1,  1.0328],
#     [ 0, 0, 0,       1]])

Blist = np.array([[0.1864,	0,0,	0,	0,	1],[0.9675,	0,	0,	0,	-1,	0],[-0.0073,	0,	0,	0,	0,	1],[0.518,	0,	0,	0,	-1,	0],[0.183,	0,	0,	0,	0,	1],[0.168,	0,	0,	0,	-1,	0],[0,	0,	0,	0,	0,	1]]).T
eomg = 0.1
ev = 0.001
#thetalist0 = np.array([0,0,0.01,0,0,0,0])
thetalist0 = np.ones(7)*np.pi/1
thetalist_IK = r.IKinBody(Blist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(rad): ", thetalist_IK[0])
print(">>> Result of IK(deg): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi))))
print(">>> Result of IK(deg,%): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

# Apply Joint Angle Constrains
for i in range(7):
    if thetalist_IK[0][i]*(180/np.pi)%360 > 180:
        thetalist_IK[0][i] = thetalist_IK[0][i] - np.pi
print(">>> Result of IK(deg,%,const): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

>>> Result of IK(rad):  [200.88761068  31.76328324 233.05470005   2.70301826 -49.28424812
 132.84740778 -96.3986608 ]
>>> Result of IK(deg):  11510.01224834774,1819.9020732601898,13353.05070859546,154.8715380004641,-2823.7794134951905,7611.595785064527,-5523.236414558892
>>> Result of IK(deg,%):  350.01224834774075,19.90207326018981,33.05070859545958,154.8715380004641,56.22058650480949,51.59578506452726,236.76358544110826
>>> Result of IK(deg,%,const):  170.01224834774075,19.90207326018981,33.05070859545958,154.8715380004641,56.22058650480949,51.59578506452726,56.76358544110735


# 6 DOF

In [54]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

T = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2650],
    [ 0, 0, 0,       1]])

# T = np.array([
#     [ 0, 0,-1, -0.9675],
#     [ 0, 1, 0, -0.1864], 
#     [ 1, 0, 0,  0.2995], 
#     [ 0, 0, 0,       1]])

Slist = np.array([[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T
eomg = 0.001
ev = 0.001
#thetalist0 = np.array([0,np.pi/0.1,0,0,0,0,0])
thetalist0 = np.ones(6)*np.pi/0.01
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(rad): ", thetalist_IK[0])
print(">>> Result of IK(deg): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi))))
print(">>> Result of IK(deg,%): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

>>> Result of IK(rad):  [-4.13540164e+08  6.39234778e+09  1.72237838e+08  1.73227707e+09
  2.41303124e+08 -8.12461985e+09]
>>> Result of IK(deg):  -23694106032.681202,366254548953.01245,9868501174.256493,99252164869.72464,13825650581.847212,-465506427590.59064
>>> Result of IK(deg,%):  287.31879806518555,33.012451171875,94.2564926147461,349.7246398925781,341.84721183776855,9.40936279296875
