## Import Modules

In [244]:
import importlib
import numpy as np
import RoboticsCore as r
importlib.reload(r)

<module 'RoboticsCore' from 'd:\\MECH639\\mech639_pybullet\\RoboticsCore.py'>

# Validation Robotics Core

## VecTose3

In [211]:
V = np.array([1, 2, 3, 4, 5, 6])

r.VecTose3(V)

array([[ 0., -6.,  5.,  1.],
       [ 6.,  0., -4.,  2.],
       [-5.,  4.,  0.,  3.],
       [ 0.,  0.,  0.,  0.]])

## se3ToVec

In [241]:
se3mat = np.array([[ 0, -6,  5, 1],
                    [ 6,  0, -4, 2],
                    [-5,  4,  0, 3],
                    [ 0,  0,  0, 0]])
r.se3ToVec(se3mat)

array([1, 2, 3, 4, 5, 6])

## Adjoint

In [221]:
T = np.array([[1, 0,  0, 0],
                [0, 0, -1, 0],
                [0, 1,  0, 3],
                [0, 0,  0, 1]])

r.Adjoint(T)

array([[ 1.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0., -1.,  3.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.]])

## MatrixExp6

In [243]:
se3mat = np.array([[0,          0,           0,          0],
                    [0,          0, -1.57079632, 2.35619449],
                    [0, 1.57079632,           0, 2.35619449],
                    [0,          0,           0,          0]])
r.MatrixExp6(se3mat, formula=1)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  6.79489676e-09, -1.00000000e+00,
         1.01923451e-08],
       [ 0.00000000e+00,  1.00000000e+00,  6.79489676e-09,
         3.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

## Jacobian

In [222]:
Blist = np.array([[   0,   0.2, 0.2, 0, 0, 1],
                    [   2,     0,   3, 1, 0, 0],
                    [   0,     2,   1, 0, 1, 0],
                    [ 0.2,   0.3, 0.4, 1, 0, 0]]).T
thetalist = np.array([0.2, 1.1, 0.1, 1.2])

print(Blist)
r.JacobianBody(Blist, thetalist)

[[0.  2.  0.  0.2]
 [0.2 0.  2.  0.3]
 [0.2 3.  1.  0.4]
 [0.  1.  0.  1. ]
 [0.  0.  1.  0. ]
 [1.  0.  0.  0. ]]


array([[ 2.42667378,  1.68606002,  0.56410831,  0.2       ],
       [-1.61330295,  2.78042027,  1.38832734,  0.3       ],
       [-2.26283471,  1.75945234, -1.60607945,  0.4       ],
       [-0.04528405,  0.99500417,  0.        ,  1.        ],
       [ 0.74359313,  0.09304865,  0.36235775,  0.        ],
       [-0.66709716,  0.03617541, -0.93203909,  0.        ]])

In [226]:
Slist = np.array([[  0, 0.2, 0.2, 0, 0, 1],
                    [  2,   0,   3, 1, 0, 0],
                    [  0,   2,   1, 0, 1, 0],
                    [0.2, 0.3, 0.4, 1, 0, 0]]).T
thetalist = np.array([0.2, 1.1, 0.1, 1.2])

r.JacobianBody(Blist, thetalist)


array([[ 2.42667378,  1.68606002,  0.56410831,  0.2       ],
       [-1.61330295,  2.78042027,  1.38832734,  0.3       ],
       [-2.26283471,  1.75945234, -1.60607945,  0.4       ],
       [-0.04528405,  0.99500417,  0.        ,  1.        ],
       [ 0.74359313,  0.09304865,  0.36235775,  0.        ],
       [-0.66709716,  0.03617541, -0.93203909,  0.        ]])

## se3 -> SE3 --> PASS

In [45]:
#se3mat = np.array([[0, 0, 0, 0], [0, 0, -1.57079632, 2.35619449], [0, 1.57079632, 0, 2.35619449], [0, 0, 0, 0]])
#se3mat = np.array([[0, 0, 0, 0], [0, 0, -1.570, 2.356], [0, 1.570, 0, 2.356], [0, 0, 0, 0]]) # Pitch h=0
se3mat = np.array([[0, 0, 0, 3], [0, 0, 1.0, 2.0], [0, -1.0, 0, 10.0], [0, 0, 0, 0]])
print(r.MatrixExp6(se3mat, formula=1))
print(r.MatrixExp6(se3mat, formula=2))
print(r.MatrixExp6(se3mat, formula=1)-r.MatrixExp6(se3mat, formula=2))

[[ 1.          0.          0.          3.        ]
 [ 0.          0.54030231  0.84147098  6.27991891]
 [ 0.         -0.84147098  0.54030231  7.49531446]
 [ 0.          0.          0.          1.        ]]
[[ 1.          0.          0.          3.        ]
 [ 0.          0.54030231  0.84147098  6.27991891]
 [ 0.         -0.84147098  0.54030231  7.49531446]
 [ 0.          0.          0.          1.        ]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 8.8817842e-16]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]


## FK and IK Body 3DOF --> PASS

In [245]:
M = np.array([[-1, 0, 0, 0],[ 0, 1, 0, 6], [ 0, 0, -1, 2], [ 0, 0, 0, 1]])
Blist = np.array([[2, 0, 0, 0, 0, -1],[0, 1, 0, 0, 0, 0], [0, 0, 0.1, 0, 0, 1]]).T
thetalist = np.array([np.pi / 2.0, 3, np.pi])
T = r.FKinBody(M, Blist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: ", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.array([1.5, 2.5, 3])
thetalist_IK = r.IKinBody(Blist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(deg): ", thetalist_IK[0]*(180/np.pi))

print(">>> Diff between FK-IK: ",(thetalist-thetalist_IK[0])*(180/np.pi))


>>> Theta for FK(deg):  [ 90.         171.88733854 180.        ]
>>> Result of FK:  [[-1.14423775e-17  1.00000000e+00  0.00000000e+00 -5.00000000e+00]
 [ 1.00000000e+00  1.14423775e-17  0.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  1.68584073e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


[IKinBody] Root Finding with iterative Newton-Raphson:   0%|          | 3/1000 [00:00<00:00, 1002.78it/s]

>>> Result of IK(deg):  [ 90.00000022 171.88733806 180.00000022]
>>> Diff between FK-IK:  [-2.21149946e-07  4.81785054e-07 -2.18960351e-07]


## FK and IK Space 3DOF --> PASS

In [248]:
M = np.array([[-1, 0, 0, 0],[ 0, 1, 0, 6], [ 0, 0, -1, 2], [ 0, 0, 0, 1]])
Slist = np.array([[ 4, 0, 0, 0, 0, 1],[ 0, 1, 0, 0, 0, 0], [-6, 0, -0.1, 0, 0, -1]]).T
thetalist = np.array([np.pi / 2.0, 3, np.pi])
T = r.FKinSpace(M,Slist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: ", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.array([1.5, 2.5, 3])
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev, maxiter=100)
print(">>> Result of IK(deg): ", thetalist_IK[0]*(180/np.pi))
print(">>> Diff between FK-IK: ",(thetalist-thetalist_IK[0])*(180/np.pi))

>>> Theta for FK(deg):  [ 90.         171.88733854 180.        ]
>>> Result of FK:  [[-1.14423775e-17  1.00000000e+00  0.00000000e+00 -5.00000000e+00]
 [ 1.00000000e+00  1.14423775e-17  0.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  1.68584073e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


[IKinSpace] Root Finding with iterative Newton-Raphson:   3%|▎         | 3/100 [00:00<00:00, 752.66it/s]

>>> Result of IK(deg):  [ 90.00000023 171.88733805 180.00000054]
>>> Diff between FK-IK:  [-2.25507968e-07  4.92294981e-07 -5.38465668e-07]


# Validation Using IndyRP2 Info

## FK and IK Body 7 DOF --> PASS
* Preper iterations for IK = 10

In [249]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Blist = np.array([[0.1864,	0,0,	0,	0,	1],[0.9675,	0,	0,	0,	-1,	0],[-0.0073,	0,	0,	0,	0,	1],[0.518,	0,	0,	0,	-1,	0],[0.183,	0,	0,	0,	0,	1],[0.168,	0,	0,	0,	-1,	0],[0,	0,	0,	0,	0,	1]]).T
thetalist = np.ones(7)*np.pi/2.0
T = r.FKinBody(M,Blist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: \n", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.zeros(7)
thetalist_IK = r.IKinBody(Blist, M, T, thetalist0, eomg, ev, maxiter=10)
print(">>> Result of IK(deg): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)])
print(">>> Result of IK(deg,%): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)%360])
print(">>> Diff between FK-IK(deg): ",[round(x,2) for x in (thetalist*(180/np.pi)-(thetalist_IK[0]*(180/np.pi)%360))])

TT = r.FKinBody(M,Blist,thetalist_IK[0])
print(">>> Result of FK': \n", TT)
print(">>> Mean of FK-IK(T): ", np.mean(T-TT))
print(">>> Diff between FK-IK(T): \n",T-TT)


>>> Theta for FK(deg):  [90. 90. 90. 90. 90. 90. 90.]
>>> Result of FK: 
 [[ 3.33066907e-16 -1.00000000e+00  2.22044605e-16 -1.56300000e-01]
 [ 1.00000000e+00  3.33066907e-16  2.22044605e-16  2.66500000e-01]
 [-2.22044605e-16  2.22044605e-16  1.00000000e+00  1.87620000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


[IKinBody] Root Finding with iterative Newton-Raphson: 100%|██████████| 10/10 [00:00<00:00, 557.40it/s]

>>> Result of IK(deg):  [221.73, -803.12, -78.45, -174.19, -799.19, 261.98, 942.5]
>>> Result of IK(deg,%):  [221.73, 276.88, 281.55, 185.81, 280.81, 261.98, 222.5]
>>> Diff between FK-IK(deg):  [-131.73, -186.88, -191.55, -95.81, -190.81, -171.98, -132.5]
>>> Result of FK': 
 [[ 3.19915705e-04 -9.99999933e-01 -1.77700869e-04 -1.56303394e-01]
 [ 9.99999931e-01  3.19949528e-04 -1.90342416e-04  2.66572293e-01]
 [ 1.90399258e-04 -1.77639963e-04  9.99999966e-01  1.87630779e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Mean of FK-IK(T):  -2.882724043190648e-05
>>> Diff between FK-IK(T): 
 [[-3.19915705e-04 -6.69618307e-08  1.77700869e-04  3.39357775e-06]
 [ 6.92989703e-08 -3.19949528e-04  1.90342416e-04 -7.22928933e-05]
 [-1.90399258e-04  1.77639963e-04  3.39039175e-08 -1.07791528e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


## FK and IK Space 7 DOF --> PASS
* Preper iterations for IK = 10

In [235]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Slist = np.array([[0,0,0,0,0,1],[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T
thetalist = np.ones(7)*np.pi/2.0
T = r.FKinSpace(M,Slist,thetalist)

print(">>> Theta for FK(deg): ", thetalist*(180/np.pi))
print(">>> Result of FK: \n", T)

eomg = 0.0001
ev = 0.0001
thetalist0 = np.zeros(7)
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev, maxiter=10)
print(">>> Result of IK(deg): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)])
print(">>> Result of IK(deg,%): ", [round(x,2) for x in thetalist_IK[0]*(180/np.pi)%360])
print(">>> Diff between FK-IK(deg): ",[round(x,2) for x in (thetalist*(180/np.pi)-(thetalist_IK[0]*(180/np.pi)%360))])

TT = r.FKinSpace(M,Slist,thetalist_IK[0])
print(">>> Result of FK': \n", TT)
print(">>> Mean of FK-IK(T): ", np.mean(T-TT))
print(">>> Diff between FK-IK(T): \n",T-TT)

>>> Theta for FK(deg):  [90. 90. 90. 90. 90. 90. 90.]
>>> Result of FK: 
 [[ 3.33066907e-16 -1.00000000e+00  2.22044605e-16 -1.56300000e-01]
 [ 1.00000000e+00  3.33066907e-16  2.22044605e-16  2.66500000e-01]
 [-2.22044605e-16  2.22044605e-16  1.00000000e+00  1.87620000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


[IKinSpace] Root Finding with iterative Newton-Raphson: 100%|██████████| 10/10 [00:00<00:00, 401.33it/s]

>>> Result of IK(deg):  [221.73, -803.12, -78.45, -174.19, -799.19, 261.98, 942.5]
>>> Result of IK(deg,%):  [221.73, 276.88, 281.55, 185.81, 280.81, 261.98, 222.5]
>>> Diff between FK-IK(deg):  [-131.73, -186.88, -191.55, -95.81, -190.81, -171.98, -132.5]
>>> Result of FK': 
 [[ 3.19915704e-04 -9.99999933e-01 -1.77700868e-04 -1.56753688e-01]
 [ 9.99999931e-01  3.19949527e-04 -1.90342415e-04  2.66089965e-01]
 [ 1.90399258e-04 -1.77639962e-04  9.99999966e-01  1.87630771e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Mean of FK-IK(T):  2.9466984059751883e-05
>>> Diff between FK-IK(T): 
 [[-3.19915704e-04 -6.69618302e-08  1.77700868e-04  4.53687576e-04]
 [ 6.92989700e-08 -3.19949527e-04  1.90342415e-04  4.10034787e-04]
 [-1.90399258e-04  1.77639962e-04  3.39039172e-08 -1.07705615e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


## FK in Body and Space 7 DOF --> PASS

In [254]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Blist = np.array([
    [ 0.1864,0,0,0,	0,1],
    [-0.9675,0,0,0,-1,0],
    [-0.0073,0,0,0,	0,1],
    [ -0.518,0,0,0,-1,0],
    [  0.183,0,0,0,	0,1],
    [ -0.168,0,0,0,-1,0],
    [      0,0,0,0,	0,1]]).T
Slist = np.array([
    [      0,0,0,0, 0,1],
    [ 0.2995,0,0,0,-1,0],
    [-0.1937,0,0,0, 0,1],
    [  0.749,0,0,0,-1,0],
    [-0.0034,0,0,0, 0,1],
    [  1.099,0,0,0,-1,0],
    [-0.1864,0,0,0, 0,1]]).T

#thetalist = np.ones(7)*np.pi/2.0
thetalist = [0,0,90,0,0,90,0]

Ts = r.FKinSpace(M,Slist,thetalist)
Tb = r.FKinBody(M,Blist,thetalist)
print(">>> Result of FKBody': \n", Tb)
print(">>> Result of FKSpace': \n", Ts)
print(">>> Diff between Tb-Ts: \n",Tb-Ts)


>>> Result of FKBody': 
 [[ 0.20076997 -0.89399666  0.40057632  0.06077065]
 [-0.40057632 -0.44807362 -0.79923003 -0.33124158]
 [ 0.89399666  0.         -0.44807362  1.02372363]
 [ 0.          0.          0.          1.        ]]
>>> Result of FKSpace': 
 [[ 0.20076997 -0.89399666  0.40057632  0.06077065]
 [-0.40057632 -0.44807362 -0.79923003 -0.33124158]
 [ 0.89399666  0.         -0.44807362  1.02372363]
 [ 0.          0.          0.          1.        ]]
>>> Diff between Tb-Ts: 
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.20656826e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.38618023e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


## IK in Body and Space 7 DOF --> PASS

In [238]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

Blist = np.array([[0.1864,	0,0,	0,	0,	1],[0.9675,	0,	0,	0,	-1,	0],[-0.0073,	0,	0,	0,	0,	1],[0.518,	0,	0,	0,	-1,	0],[0.183,	0,	0,	0,	0,	1],[0.168,	0,	0,	0,	-1,	0],[0,	0,	0,	0,	0,	1]]).T
Slist = np.array([[0,0,0,0,0,1],[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T

thetalist = np.ones(7)*np.pi/2.0
Ts = r.FKinSpace(M,Slist,thetalist)

eomg = 0.0001
ev = 0.0001
thetalist0 = thetalist - np.random.rand(7)*0.01
maxiter = 1

thetalist_IKb = r.IKinBody(Blist, M, T, thetalist0, eomg, ev, maxiter=maxiter)
thetalist_IKs = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev, maxiter=maxiter)

print(">>> Result of IKs(deg,%): ", [round(x,2) for x in thetalist_IKs[0]*(180/np.pi)%360])
print(">>> Result of IKb(deg,%): ", [round(x,2) for x in thetalist_IKb[0]*(180/np.pi)%360])
print(">>> Mean between IKs-IKb(deg): ",np.mean((thetalist_IKs[0]*(180/np.pi)%360)-(thetalist_IKb[0]*(180/np.pi)%360)))
print(">>> Diff between IKs-IKb(deg): ",[round(x,2) for x in ((thetalist_IKs[0]*(180/np.pi)%360)-(thetalist_IKb[0]*(180/np.pi)%360))])

Ts = r.FKinSpace(M,Slist,thetalist_IKs[0])
Tb = r.FKinBody(M,Blist,thetalist_IKb[0])
print(">>> Result of FKs': \n", Ts)
print(">>> Result of FKb': \n", Tb)
print(">>> Mean of FKs-FKb: ", np.mean(Ts-Tb))
print(">>> Diff between FKs-FKb: \n",Ts-Tb)


[IKinBody] Root Finding with iterative Newton-Raphson: 100%|██████████| 1/1 [00:00<00:00, 250.81it/s]
[IKinSpace] Root Finding with iterative Newton-Raphson: 100%|██████████| 1/1 [00:00<00:00, 334.50it/s]

>>> Result of IKs(deg,%):  [89.9, 89.9, 89.88, 89.99, 90.09, 90.13, 90.11]
>>> Result of IKb(deg,%):  [89.9, 89.9, 89.88, 89.99, 90.09, 90.13, 90.11]
>>> Mean between IKs-IKb(deg):  -2.0301221021717147e-15
>>> Diff between IKs-IKb(deg):  [0.0, -0.0, -0.0, 0.0, 0.0, 0.0, -0.0]
>>> Result of FKs': 
 [[ 3.95318056e-05 -9.99999999e-01 -3.71306237e-05 -1.56382966e-01]
 [ 9.99999999e-01  3.95307455e-05  2.85510717e-05  2.66585087e-01]
 [-2.85496038e-05 -3.71317523e-05  9.99999999e-01  1.87620632e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Result of FKb': 
 [[ 3.95318056e-05 -9.99999999e-01 -3.71306237e-05 -1.56288877e-01]
 [ 9.99999999e-01  3.95307455e-05  2.85510717e-05  2.66512739e-01]
 [-2.85496038e-05 -3.71317523e-05  9.99999999e-01  1.87620633e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
>>> Mean of FKs-FKb:  -1.3589602791648305e-06
>>> Diff between FKs-FKb: 
 [[ 2.73761049e-18  0.00000000e+00  2.22153025e-16 -9.40890005e-05]


# 7 DOF

In [106]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,0,0,0,0,0,0]
T = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,30,0,-60,0,30,0]
# T = np.array([
#     [1, 0, 0,        -0.0497],
#     [ 0, 1, 0, -0.1864],
#     [ 0, 0, 1,  1.1599],
#     [ 0, 0, 0,       1]])

# T = np.array([
#     [ 0, 0,-1, -0.9675],
#     [ 0, 1, 0, -0.1864], 
#     [ 1, 0, 0,  0.2995], 
#     [ 0, 0, 0,       1]])

Slist = np.array([[0,0,0,0,0,1],[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T
eomg = 999999
ev = 0.001
thetalist0 = np.array([0,0,np.pi/2.0,0,0,0,0])
#thetalist0 = np.ones(7)*np.pi/0.001
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(rad): ", thetalist_IK[0])
print(">>> Result of IK(deg): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi))))
print(">>> Result of IK(deg,%): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

>>> Result of IK(rad):  [-152.13030523   64.79403474 -138.29620881  -58.42568669  145.57403555
   19.69317382  -14.75529024]
>>> Result of IK(deg):  -8716.4244255022,3712.4247280368013,-7923.789087531694,-3347.5452625855914,8340.777843654909,1128.3357448397853,-845.4158559876978
>>> Result of IK(deg,%):  283.5755744977996,112.4247280368013,356.21091246830565,252.45473741440856,60.77784365490879,48.33574483978532,234.5841440123022


In [121]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,0,0,0,0,0,0]
T = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

# [0,30,0,-60,0,30,0]
# T = np.array([
#     [1, 0, 0,        -0.0497],
#     [ 0, 1, 0, -0.1864],
#     [ 0, 0, 1,  1.1599],
#     [ 0, 0, 0,       1]])

# [0,45,0,-90,0,45,0]
# T = np.array([
#     [1, 0, 0,  -0.0704],
#     [ 0, 1, 0, -0.1864],
#     [ 0, 0, 1,  1.0328],
#     [ 0, 0, 0,       1]])

Blist = np.array([[0.1864,	0,0,	0,	0,	1],[0.9675,	0,	0,	0,	-1,	0],[-0.0073,	0,	0,	0,	0,	1],[0.518,	0,	0,	0,	-1,	0],[0.183,	0,	0,	0,	0,	1],[0.168,	0,	0,	0,	-1,	0],[0,	0,	0,	0,	0,	1]]).T
eomg = 0.1
ev = 0.001
#thetalist0 = np.array([0,0,0.01,0,0,0,0])
thetalist0 = np.ones(7)*np.pi/1
thetalist_IK = r.IKinBody(Blist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(rad): ", thetalist_IK[0])
print(">>> Result of IK(deg): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi))))
print(">>> Result of IK(deg,%): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

# Apply Joint Angle Constrains
for i in range(7):
    if thetalist_IK[0][i]*(180/np.pi)%360 > 180:
        thetalist_IK[0][i] = thetalist_IK[0][i] - np.pi
print(">>> Result of IK(deg,%,const): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

>>> Result of IK(rad):  [200.88761068  31.76328324 233.05470005   2.70301826 -49.28424812
 132.84740778 -96.3986608 ]
>>> Result of IK(deg):  11510.01224834774,1819.9020732601898,13353.05070859546,154.8715380004641,-2823.7794134951905,7611.595785064527,-5523.236414558892
>>> Result of IK(deg,%):  350.01224834774075,19.90207326018981,33.05070859545958,154.8715380004641,56.22058650480949,51.59578506452726,236.76358544110826
>>> Result of IK(deg,%,const):  170.01224834774075,19.90207326018981,33.05070859545958,154.8715380004641,56.22058650480949,51.59578506452726,56.76358544110735


# 6 DOF

In [54]:
M = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2670],
    [ 0, 0, 0,       1]])

T = np.array([
    [1, 0, 0,        0],
    [ 0, 1, 0, -0.1864],
    [ 0, 0, 1,  1.2650],
    [ 0, 0, 0,       1]])

# T = np.array([
#     [ 0, 0,-1, -0.9675],
#     [ 0, 1, 0, -0.1864], 
#     [ 1, 0, 0,  0.2995], 
#     [ 0, 0, 0,       1]])

Slist = np.array([[-0.2995,0,0,0,-1,0],[-0.1937,0,0,0,0,1],[-0.749,0,0,0,-1,0],[-0.0034,0,0,0,0,1],[-1.099,0,0,0,-1,0],[-0.1864,0,0,0,0,1]]).T
eomg = 0.001
ev = 0.001
#thetalist0 = np.array([0,np.pi/0.1,0,0,0,0,0])
thetalist0 = np.ones(6)*np.pi/0.01
thetalist_IK = r.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
print(">>> Result of IK(rad): ", thetalist_IK[0])
print(">>> Result of IK(deg): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi))))
print(">>> Result of IK(deg,%): ", ",".join(map(str,thetalist_IK[0]*(180/np.pi)%360)))

>>> Result of IK(rad):  [-4.13540164e+08  6.39234778e+09  1.72237838e+08  1.73227707e+09
  2.41303124e+08 -8.12461985e+09]
>>> Result of IK(deg):  -23694106032.681202,366254548953.01245,9868501174.256493,99252164869.72464,13825650581.847212,-465506427590.59064
>>> Result of IK(deg,%):  287.31879806518555,33.012451171875,94.2564926147461,349.7246398925781,341.84721183776855,9.40936279296875
